### ISSUE TITLE
Errors when load_path ./Params/Combine/latest_net_DE_.pkl

### ISSUE THREAD

**Issue by Sunny-Island** [IGLICT/DeepFaceDrawing-Jittor#25]
Errors when run `python3.7 demo.py` Could you please give me some advice?
load_path ./Params/Combine/latest_net_DE_.pkl

```

Assertion failed:
Traceback (most recent call last):
  File "demo.py", line 13, in <module>
    ui = WindowUI()
  File "/home/zhaojiabei/DeepFaceDrawing-Jittor/WindowUI.py", line 43, in __init__
    self.input_scene = InputGraphicsScene(self.modes, self.brush_size,self.output_scene)
  File "/home/zhaojiabei/DeepFaceDrawing-Jittor/Input_mouse_event.py", line 105, in __init__
    self.predict_shadow()
  File "/home/zhaojiabei/DeepFaceDrawing-Jittor/Input_mouse_event.py", line 273, in predict_shadow
    sex=self.sex)
  File "/home/zhaojiabei/DeepFaceDrawing-Jittor/models/AE_Model.py", line 97, in get_inter
    generated_f = self.get_latent(input_image)
  File "/home/zhaojiabei/DeepFaceDrawing-Jittor/models/AE_Model.py", line 80, in get_latent
    mus_mouth = self.net_encoder(input_image)
  File "/home/zhaojiabei/anaconda3/envs/face_drawing/lib/python3.7/site-packages/jittor/__init__.py", line 511, in __call__
    return self.execute(*args, **kw)
  File "/home/zhaojiabei/DeepFaceDrawing-Jittor/models/networks.py", line 199, in execute
    mu = self.fc_mu(ten)
  File "/home/zhaojiabei/anaconda3/envs/face_drawing/lib/python3.7/site-packages/jittor/__init__.py", line 511, in __call__
    return self.execute(*args, **kw)
  File "/home/zhaojiabei/anaconda3/envs/face_drawing/lib/python3.7/site-packages/jittor/nn.py", line 1303, in execute
    x = layer(x)
  File "/home/zhaojiabei/anaconda3/envs/face_drawing/lib/python3.7/site-packages/jittor/__init__.py", line 511, in __call__
    return self.execute(*args, **kw)
  File "/home/zhaojiabei/anaconda3/envs/face_drawing/lib/python3.7/site-packages/jittor/nn.py", line 378, in execute
    x = matmul_transpose(x, self.weight)
  File "/home/zhaojiabei/anaconda3/envs/face_drawing/lib/python3.7/site-packages/jittor/nn.py", line 30, in matmul_transpose
    assert a.shape[-1] == b.shape[-1]
AssertionError


```

**Comment by Sunny-Island** [comment]
Full infomation:
```
load_path ./Params/Combine/latest_net_DE_mouth.pkl
[w 0124 01:30:28.930117 76 cuda_device_allocator.cc:27] Unable to alloc cuda device memory, use unify memory instead. This may cause low performance.
[i 0124 01:30:28.930129 76 cuda_device_allocator.cc:29] 
=== display_memory_info ===
 total_cpu_ram: 125.8GB total_cuda_ram: 11.91GB
 hold_vars: 1630 lived_vars: 3536 lived_ops: 3536
 update queue: 1524/1524
 name: sfrl is_cuda: 1 used: 3.857GB(99.6%) unused: 17.66MB(0.445%) total: 3.874GB
 name: sfrl is_cuda: 0 used: 3.892GB(99.6%) unused: 17.66MB(0.441%) total: 3.909GB
 name: sfrl is_cuda: 0 used:    83KB(8.11%) unused:   941KB(91.9%) total:     1MB
 cpu&gpu: 7.784GB gpu: 3.874GB cpu:  3.91GB
 
name: temp 
 used_memory:     0 B 
 unused_memory:     0 B 
===========================

[w 0124 01:30:28.951584 76 cuda_device_allocator.cc:27] Unable to alloc cuda device memory, use unify memory instead. This may cause low performance.
[i 0124 01:30:28.951595 76 cuda_device_allocator.cc:29] 
=== display_memory_info ===
 total_cpu_ram: 125.8GB total_cuda_ram: 11.91GB
 hold_vars: 1630 lived_vars: 3526 lived_ops: 3526
 update queue: 1526/1526
 name: sfrl is_cuda: 1 used: 3.892GB(99.6%) unused: 17.59MB(0.439%) total: 3.909GB
 name: sfrl is_cuda: 0 used: 3.901GB(99.3%) unused: 28.59MB(0.711%) total: 3.929GB
 name: sfrl is_cuda: 0 used:    81KB(7.91%) unused:   943KB(92.1%) total:     1MB
 cpu&gpu: 7.839GB gpu: 3.909GB cpu:  3.93GB
 
name: temp 
 used_memory:     0 B 
 unused_memory:     0 B 
===========================

[w 0124 01:30:28.981289 76 cuda_device_allocator.cc:27] Unable to alloc cuda device memory, use unify memory instead. This may cause low performance.
[i 0124 01:30:28.981300 76 cuda_device_allocator.cc:29] 
=== display_memory_info ===
 total_cpu_ram: 125.8GB total_cuda_ram: 11.91GB
 hold_vars: 1630 lived_vars: 3496 lived_ops: 3496
 update queue: 1538/1538
 name: sfrl is_cuda: 1 used:  3.91GB(99.5%) unused: 19.57MB(0.486%) total: 3.929GB
 name: sfrl is_cuda: 0 used: 3.917GB(99.2%) unused: 31.57MB(0.781%) total: 3.948GB
 name: sfrl is_cuda: 0 used:    72KB(7.03%) unused:   952KB(93%) total:     1MB
 cpu&gpu: 7.878GB gpu: 3.929GB cpu: 3.949GB
 
name: temp 
 used_memory:     0 B 
 unused_memory:     0 B 
===========================

[w 0124 01:30:28.994376 76 cuda_device_allocator.cc:27] Unable to alloc cuda device memory, use unify memory instead. This may cause low performance.
[i 0124 01:30:28.994387 76 cuda_device_allocator.cc:29] 
=== display_memory_info ===
 total_cpu_ram: 125.8GB total_cuda_ram: 11.91GB
 hold_vars: 1630 lived_vars: 3391 lived_ops: 3391
 update queue: 1580/1580
 name: sfrl is_cuda: 1 used: 3.932GB(99.6%) unused: 16.54MB(0.409%) total: 3.948GB
 name: sfrl is_cuda: 0 used: 3.933GB(99.6%) unused: 16.97MB(0.42%) total: 3.949GB
 name: sfrl is_cuda: 0 used:  40.5KB(3.96%) unused: 983.5KB(96%) total:     1MB
 cpu&gpu: 7.898GB gpu: 3.948GB cpu:  3.95GB
 
name: temp 
 used_memory:     0 B 
 unused_memory:     0 B 
===========================

[w 0124 01:30:29.028732 76 cuda_device_allocator.cc:27] Unable to alloc cuda device memory, use unify memory instead. This may cause low performance.
[i 0124 01:30:29.028743 76 cuda_device_allocator.cc:29] 
=== display_memory_info ===
 total_cpu_ram: 125.8GB total_cuda_ram: 11.91GB
 hold_vars: 1630 lived_vars: 3376 lived_ops: 3376
 update queue: 1586/1586
 name: sfrl is_cuda: 1 used: 3.933GB(99.6%) unused: 16.97MB(0.42%) total: 3.949GB
 name: sfrl is_cuda: 0 used: 3.933GB(99.6%) unused: 17.41MB(0.43%) total:  3.95GB
 name: sfrl is_cuda: 0 used:    36KB(3.52%) unused:   988KB(96.5%) total:     1MB
 cpu&gpu:   7.9GB gpu: 3.949GB cpu: 3.951GB
 
name: temp 
 used_memory:     0 B 
 unused_memory:     0 B 
===========================

Traceback (most recent call last):
  File "demo.py", line 13, in <module>
    ui = WindowUI()
  File "/home/zhaojiabei/DeepFaceDrawing-Jittor/WindowUI.py", line 43, in __init__
    self.input_scene = InputGraphicsScene(self.modes, self.brush_size,self.output_scene)
  File "/home/zhaojiabei/DeepFaceDrawing-Jittor/Input_mouse_event.py", line 105, in __init__
    self.predict_shadow()
  File "/home/zhaojiabei/DeepFaceDrawing-Jittor/Input_mouse_event.py", line 273, in predict_shadow
    sex=self.sex)
  File "/home/zhaojiabei/DeepFaceDrawing-Jittor/models/AE_Model.py", line 97, in get_inter
    generated_f = self.get_latent(input_image)
  File "/home/zhaojiabei/DeepFaceDrawing-Jittor/models/AE_Model.py", line 80, in get_latent
    mus_mouth = self.net_encoder(input_image)
  File "/home/zhaojiabei/anaconda3/envs/face_drawing/lib/python3.7/site-packages/jittor/__init__.py", line 511, in __call__
    return self.execute(*args, **kw)
  File "/home/zhaojiabei/DeepFaceDrawing-Jittor/models/networks.py", line 199, in execute
    mu = self.fc_mu(ten)
  File "/home/zhaojiabei/anaconda3/envs/face_drawing/lib/python3.7/site-packages/jittor/__init__.py", line 511, in __call__
    return self.execute(*args, **kw)
  File "/home/zhaojiabei/anaconda3/envs/face_drawing/lib/python3.7/site-packages/jittor/nn.py", line 1303, in execute
    x = layer(x)
  File "/home/zhaojiabei/anaconda3/envs/face_drawing/lib/python3.7/site-packages/jittor/__init__.py", line 511, in __call__
    return self.execute(*args, **kw)
  File "/home/zhaojiabei/anaconda3/envs/face_drawing/lib/python3.7/site-packages/jittor/nn.py", line 378, in execute
    x = matmul_transpose(x, self.weight)
  File "/home/zhaojiabei/anaconda3/envs/face_drawing/lib/python3.7/site-packages/jittor/nn.py", line 30, in matmul_transpose
    assert a.shape[-1] == b.shape[-1]
AssertionError
```

**Comment by Sunny-Island** [comment]
I have successfully load other pkl file, such as` latest_net_DE_eye2.pkl`
