### ISSUE TITLE
unable to run demo.py file - runtime error

### ISSUE THREAD

**Issue by Trivenu** [IGLICT/DeepFaceDrawing-Jittor#30]
got the below error while running:
on3.8 -I/home/karthik/.local/lib/python3.8/site-packages/pybind11/include
[i 0524 10:49:50.172849 52 compiler.py:898] extension_suffix: .cpython-38-x86_64-linux-gnu.so
[i 0524 10:49:50.427291 52 __init__.py:168] Total mem: 10.62GB, using 3 procs for compiling.
[i 0524 10:49:50.993130 52 jit_compiler.cc:20] Load cc_path: /usr/bin/g++
[i 0524 10:49:51.052464 52 __init__.py:249] Found mpicc(4.0.3) at /usr/bin/mpicc.
[i 0524 10:49:51.124027 52 compiler.py:653] handle pyjt_include/home/karthik/.local/lib/python3.8/site-packages/jittor/extern/mpi/inc/mpi_warper.h
Traceback (most recent call last):
  File "demo.py", line 4, in <module>
    from WindowUI import WindowUI
  File "/home/karthik/Documents/deeplearning/DeepFaceDrawing-Jittor/WindowUI.py", line 18, in <module>
    jt.flags.use_cuda = 1
**RuntimeError: Wrong inputs arguments, Please refer to examples(help(jt.flags)).**

Types of your inputs are:
 self	= flags,
 arg	= int,

The function declarations are:
 void _set_use_cuda(int v)
 void _set_use_cuda(bool v)

Failed reason:[f 0524 10:49:51.790183 52 cuda_flags.cc:30] Check failed: value==0  No CUDA found.

**Comment by tsv19su254052** [comment]
![image](https://user-images.githubusercontent.com/104857185/168894669-d0d6dc1d-d0e3-45a2-a75a-147f9418e012.png)
